export const sagaActions = {
  SET_TRANSACTIONS: "SET_TRANSACTIONS",
  SET_TRANSACTIONS_FAILED: "SET_TRANSACTIONS_FAILED",

  FETCH_TRANSACTIONS: "FETCH_TRANSACTIONS",
  FETCH_TRANSACTIONS_FAILED: "FETCH_TRANSACTIONS_FAILED",

  UPDATE_TRANSACTION: "UPDATE_TRANSACTION",
  UPDATE_TRANSACTION_FAILED: "UPDATE_TRANSACTION_FAILED",

  DELETE_TRANSACTION: "DELETE_TRANSACTION",
  DELETE_TRANSACTION_FAILED: "DELETE_TRANSACTION_FAILED",

  SEARCH_TRANSACTIONS: "SEARCH_TRANSACTIONS",
  SEARCH_TRANSACTIONS_FAILED: "SEARCH_TRANSACTIONS_FAILED",
};
