export const sagaActions = {
  SET_TRANSACTIONS: "SET_TRANSACTIONS",
  SET_TRANSACTIONS_FAILED: "SET_TRANSACTIONS_FAILED",

  FETCH_TRANSACTIONS: "FETCH_TRANSACTIONS",
  FETCH_TRANSACTIONS_FAILED: "FETCH_TRANSACTIONS_FAILED",
};
